/** Frontend screen matrix — must stay aligned with platform-core/economic-catalog.mjs */

export const ECC_ACTIONS = [
  { id: 'discover', label: 'Discover', accent: 'cyan' },
  { id: 'observe', label: 'Observe', accent: 'cyan' },
  { id: 'transact', label: 'Transact', accent: 'purple' },
  { id: 'reconcile', label: 'Reconcile', accent: 'green' },
  { id: 'settle', label: 'Settle', accent: 'green' },
  { id: 'forecast', label: 'Forecast', accent: 'purple' },
  { id: 'automate', label: 'Automate', accent: 'purple' },
  { id: 'diagnose', label: 'Diagnose', accent: 'orange' },
  { id: 'recover', label: 'Recover', accent: 'green' },
  { id: 'audit', label: 'Audit', accent: 'cyan' },
  { id: 'report', label: 'Report', accent: 'cyan' },
];

export const ECC_SCREENS = [
  { id: 'overview', label: 'Economic Home', capability: 'economic-overview', layout: 'overview', actions: ['observe', 'diagnose', 'audit', 'report'] },
  { id: 'treasury', label: 'Treasury', capability: 'treasury', layout: 'overview', actions: ['transact', 'settle', 'forecast'] },
  { id: 'ledger', label: 'General Ledger', capability: 'ledger', layout: 'grid', actions: ['observe', 'audit'] },
  { id: 'accounts', label: 'Accounts', capability: 'ledger', layout: 'grid' },
  { id: 'wallets', label: 'Wallets', capability: 'wallets', layout: 'grid', actions: ['transact'] },
  { id: 'payments', label: 'Payments', capability: 'payments', layout: 'grid', actions: ['observe', 'diagnose'] },
  { id: 'billing', label: 'Billing', capability: 'invoicing', layout: 'grid', actions: ['transact'] },
  { id: 'invoices', label: 'Invoices', capability: 'invoicing', layout: 'grid', actions: ['transact'] },
  { id: 'revenue', label: 'Revenue', capability: 'invoicing', layout: 'overview' },
  { id: 'expenses', label: 'Expenses', capability: 'expenses', layout: 'grid' },
  { id: 'settlements', label: 'Settlements', capability: 'settlements', layout: 'timeline' },
  { id: 'reconciliation', label: 'Reconciliation', capability: 'reconciliation', layout: 'grid', actions: ['reconcile'] },
  { id: 'tax', label: 'Tax', capability: 'tax', layout: 'overview' },
  { id: 'contracts', label: 'Contracts', capability: 'contracts', layout: 'grid' },
  { id: 'marketplace', label: 'Marketplace', capability: 'marketplace', layout: 'grid' },
  { id: 'earnings', label: 'Earnings', capability: 'payouts', layout: 'overview' },
  { id: 'rewards', label: 'Rewards', capability: 'rewards', layout: 'grid' },
  { id: 'ubi', label: 'UBI / Distributions', capability: 'distributions', layout: 'grid' },
  { id: 'assets', label: 'Assets', capability: 'ledger', layout: 'grid' },
  { id: 'liabilities', label: 'Liabilities', capability: 'ledger', layout: 'grid' },
  { id: 'cash-flow', label: 'Cash Flow', capability: 'treasury', layout: 'overview', actions: ['forecast'] },
  { id: 'budgets', label: 'Budgets', capability: 'budgets', layout: 'grid' },
  { id: 'forecasting', label: 'Forecasting', capability: 'forecasting', layout: 'overview', actions: ['forecast'] },
  { id: 'pricing', label: 'Pricing', capability: 'invoicing', layout: 'grid' },
  { id: 'commissions', label: 'Commissions', capability: 'commissions', layout: 'grid' },
  { id: 'fees', label: 'Fees', capability: 'payments', layout: 'grid' },
  { id: 'gateways', label: 'Gateways', capability: 'payments', layout: 'grid' },
  { id: 'fraud', label: 'Fraud', capability: 'fraud', layout: 'grid' },
  { id: 'risk', label: 'Risk', capability: 'risk', layout: 'overview' },
  { id: 'compliance', label: 'Compliance', capability: 'audit', layout: 'grid' },
  { id: 'disputes', label: 'Disputes', capability: 'payments', layout: 'timeline' },
  { id: 'refunds', label: 'Refunds', capability: 'payments', layout: 'grid' },
  { id: 'payouts', label: 'Payouts', capability: 'payouts', layout: 'grid' },
  { id: 'beneficiaries', label: 'Beneficiaries', capability: 'payouts', layout: 'grid' },
  { id: 'customers', label: 'Customers', capability: 'crm', layout: 'grid', actions: ['transact'] },
  { id: 'vendors', label: 'Vendors', capability: 'crm', layout: 'grid' },
  { id: 'currencies', label: 'Currencies', capability: 'economic-overview', layout: 'grid' },
  { id: 'exchange-rates', label: 'Exchange Rates', capability: 'fx', layout: 'grid' },
  { id: 'automation', label: 'Economic Automation', capability: 'workflow-automation', layout: 'timeline', actions: ['automate'] },
  { id: 'reports', label: 'Reports', capability: 'audit', layout: 'report', actions: ['report'] },
  { id: 'audit', label: 'Audit', capability: 'audit', layout: 'grid' },
  { id: 'settings', label: 'Settings', capability: 'economic-overview', layout: 'settings' },
];

export function getEconomicScreen(id) {
  return ECC_SCREENS.find((s) => s.id === id) || ECC_SCREENS[0];
}
