#!/usr/bin/env pwsh
<#
.SYNOPSIS
  Build a theme-only package directory for Docker mounts (Stage 2).

.DESCRIPTION
  Creates/refreshes NextGenTutors-BeyondInfinity/ with directory junctions
  for theme folders and hardlinks (fallback: copy) for root theme files.
  Does NOT delete originals at repo root. Non-destructive.
#>
param(
  [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
  [string]$ThemeDirName = 'NextGenTutors-BeyondInfinity'
)

$ErrorActionPreference = 'Stop'
$themeDir = Join-Path $Root $ThemeDirName
New-Item -ItemType Directory -Force -Path $themeDir | Out-Null

$dirLinks = @(
  'assets', 'inc', 'templates', 'template-parts', 'page-templates',
  'prototypes', 'content', 'automations', 'tests'
)

$pageFiles = @(Get-ChildItem -Path $Root -Filter 'page-*.php' -File -ErrorAction SilentlyContinue | ForEach-Object { $_.Name })
$rootFiles = @(
  'style.css', 'functions.php', 'header.php', 'footer.php', 'index.php',
  'front-page.php', 'home.php', 'page.php', 'single.php', 'single-tutors.php',
  'archive.php', 'archive-tutors.php', 'searchform.php', 'comments.php',
  '404.php', 'admin-dashboard.php', 'screenshot.png'
) + $pageFiles

function Ensure-DirJunction([string]$name) {
  $src = Join-Path $Root $name
  $dst = Join-Path $themeDir $name
  if (-not (Test-Path -LiteralPath $src)) {
    Write-Host "SKIP missing dir $name"
    return
  }
  if (Test-Path -LiteralPath $dst) {
    $item = Get-Item -LiteralPath $dst -Force
    if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
      Write-Host "OK junction $name"
      return
    }
    Write-Host "WARN $name exists as real path - not replacing"
    return
  }
  cmd /c "mklink /J `"$dst`" `"$src`""
}

function Ensure-FileLink([string]$name) {
  $src = Join-Path $Root $name
  $dst = Join-Path $themeDir $name
  if (-not (Test-Path -LiteralPath $src)) {
    Write-Host "SKIP missing file $name"
    return
  }
  if (Test-Path -LiteralPath $dst) {
    Write-Host "OK file $name"
    return
  }
  try {
    New-Item -ItemType HardLink -Path $dst -Target $src | Out-Null
    Write-Host "HARDLINK $name"
  } catch {
    Copy-Item -LiteralPath $src -Destination $dst -Force
    Write-Host "COPY $name"
  }
}

foreach ($d in $dirLinks) { Ensure-DirJunction $d }
foreach ($f in ($rootFiles | Select-Object -Unique)) { Ensure-FileLink $f }

Set-Content -Path (Join-Path $themeDir '.ngt-theme-package') -Encoding UTF8 -Value @(
  '# Packaged theme root for Docker / distribution',
  '# Source of truth remains the monorepo theme files linked from here.',
  '# Generated by scripts/sync-beyondinfinity-theme.ps1'
)

Write-Host ("THEME_PACKAGE=" + $themeDir)
Get-ChildItem $themeDir | Select-Object Name, Mode, LinkType | Format-Table -AutoSize
