<?php
/**
 * Scans HTML artifacts and old theme for import candidates.
 *
 * @package NextGenCompanion
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Reads workspace inventories + optional external paths.
 */
class NGC_UI_Import_Scanner {

	/**
	 * Default artifact paths (override via filter).
	 *
	 * @return array<int, array<string, string>>
	 */
	public static function artifact_paths() {
		$paths = [
			[
				'label' => 'nextgentutors_final',
				'path'  => 'C:/Users/marvi/Desktop/nextgentutors-full-website/Implementation/Research-Artifacts/nextgentutors_final.html',
			],
			[
				'label' => 'nextgentutors_complete',
				'path'  => 'C:/Users/marvi/Desktop/nextgentutors-full-website/Implementation/Research-Artifacts/nextgentutors_complete (1).html',
			],
			[
				'label' => 'nextgen_tutors_redesign',
				'path'  => 'C:/Users/marvi/Desktop/nextgentutors-full-website/Implementation/Research-Artifacts/nextgen_tutors_redesign.html',
			],
			[
				'label' => 'nextgen_tutors_full_redesign_v2',
				'path'  => 'C:/Users/marvi/Desktop/nextgentutors-full-website/Implementation/Research-Artifacts/nextgen_tutors_full_redesign_v2.html',
			],
		];

		return apply_filters( 'ngc_ui_artifact_paths', $paths );
	}

	/**
	 * Inventory JSON from repo docs (generated by analyze-ui-artifacts.mjs).
	 *
	 * @return array<string, mixed>|null
	 */
	public static function load_repo_inventory() {
		$candidates = [
			ABSPATH . '../docs/ui-library/inventories/html-artifacts.json',
			WP_CONTENT_DIR . '/../docs/ui-library/inventories/html-artifacts.json',
		];

		if ( defined( 'NGC_PLUGIN_DIR' ) ) {
			$candidates[] = dirname( NGC_PLUGIN_DIR ) . '/docs/ui-library/inventories/html-artifacts.json';
		}

		foreach ( $candidates as $path ) {
			if ( is_readable( $path ) ) {
				$data = json_decode( (string) file_get_contents( $path ), true );
				return is_array( $data ) ? $data : null;
			}
		}

		return null;
	}

	/**
	 * Full scan result for admin UI.
	 *
	 * @return array<string, mixed>
	 */
	public static function scan() {
		$inventory = self::load_repo_inventory();
		$html      = [];

		if ( $inventory ) {
			foreach ( $inventory as $row ) {
				$html[] = [
					'label'    => $row['label'] ?? '',
					'found'    => empty( $row['error'] ),
					'sections' => $row['sectionPurposes'] ?? [],
					'risks'    => $row['risks'] ?? [],
					'dynamic'  => array_keys( $row['dynamicFields'] ?? [] ),
				];
			}
		} else {
			foreach ( self::artifact_paths() as $artifact ) {
				$exists = is_readable( $artifact['path'] );
				$html[] = [
					'label' => $artifact['label'],
					'found' => $exists,
					'path'  => $artifact['path'],
				];
			}
		}

		$heading_sources = [];
		if ( $inventory ) {
			foreach ( $inventory as $row ) {
				$heading_sources[] = [
					'source'   => $row['label'] ?? '',
					'headings' => $row['headings'] ?? [],
				];
			}
		}

		return [
			'scanned_at'  => gmdate( 'c' ),
			'html'        => $html,
			'duplicates'  => NGC_UI_Duplicate_Detector::scan_headings( $heading_sources ),
			'components'  => NGC_UI_Component_Registry::definitions(),
			'providers'   => NGC_UI_Provider_Registry::verification_report(),
		];
	}

	/**
	 * Import selected CMS fields (preview-only unless $commit true).
	 *
	 * @param array<int, array<string, mixed>> $items Items to import.
	 * @param bool                             $commit Persist.
	 * @return array<string, mixed>
	 */
	public static function import_items( $items, $commit = false ) {
		$log = [
			'imported' => 0,
			'skipped'  => 0,
			'conflicts'=> [],
			'preview'  => ! $commit,
		];

		if ( ! class_exists( 'NGC_Section_CMS' ) ) {
			$log['error'] = 'NGC_Section_CMS unavailable';
			return $log;
		}

		foreach ( $items as $item ) {
			$page    = sanitize_key( $item['page_key'] ?? '' );
			$section = sanitize_key( $item['section_key'] ?? '' );
			$field   = sanitize_key( $item['field_key'] ?? '' );
			$value   = isset( $item['value'] ) ? wp_kses_post( (string) $item['value'] ) : '';

			if ( ! $page || ! $section ) {
				++$log['skipped'];
				continue;
			}

			if ( $field && '' !== $value ) {
				if ( NGC_UI_Duplicate_Detector::exists_in_cms( $value, $page, $section ) ) {
					++$log['skipped'];
					$log['conflicts'][] = compact( 'page', 'section', 'field' );
					continue;
				}
				if ( $commit ) {
					NGC_Section_CMS::upsert_section_field( $page, $section, $field, $value );
				}
				++$log['imported'];
				continue;
			}

			if ( 'home' === $page && in_array( $section, NGC_Section_CMS::section_keys(), true ) ) {
				if ( $commit ) {
					NGC_Section_CMS::save_section( $page, $section, NGC_Section_CMS::default_content( $section ), true );
				}
				++$log['imported'];
				continue;
			}

			++$log['skipped'];
		}

		if ( $commit && class_exists( 'NGC_Section_CMS' ) && empty( $items ) ) {
			$seed = NGC_Section_CMS::seed_research_copy( false );
			$log['imported'] += (int) ( $seed['imported'] ?? 0 );
			$log['skipped']  += (int) ( $seed['skipped'] ?? 0 );
		}

		if ( $commit ) {
			update_option( 'ngc_ui_last_import', gmdate( 'c' ), false );
		}

		return $log;
	}
}
